name: Mi workflow

on: push

jobs:
  tareas:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar code
        uses: actions/checkout@v4
      - name: Ej1
        run: |
          pip install pytest
          pytest test.py
        
